version: '3'
services:
  # Serviço para o banco de dados MySQL
  mysql:
    image: mysql:latest
    container_name: my-sql-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tech-challenge-fiap
      MYSQL_USER: fiap
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  
  mysql-test:
    image: mysql:latest
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tech-challenge-fiap-test
      MYSQL_USER: fiap-test
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  